require("plugconf.nvim-tree")
require("plugconf.bufferline")
require("plugconf.github-theme")
require("plugconf.vim-gitgutter")
require("plugconf.vim-markdown")
require("plugconf.indent-blankline")
require("plugconf.nvim-telescope")
require("plugconf.toggleterm")
require("plugconf.treesitter")
require("plugconf.alpha")
require("plugconf.auto-pair")
require("plugconf.ultisnips")
require("plugconf.nvim-colorizer")
require("plugconf.nvim-telescope-media")
require("plugconf.hop")

