require("plugconf.vim-markdown")
require("plugconf.nvim-telescope")
require("plugconf.toggleterm")
require("plugconf.treesitter")
require("plugconf.auto-pair")
require("plugconf.nvim-colorizer")
require("plugconf.hop")
require("plugconf.nvim-web-devicon")
require("plugconf.illuminate")
-- require("plugconf.nvim-navic")
-- require("plugconf.symbols-outline")
require("plugconf.gitsigns")
require("plugconf.friendly-snippets")
require("plugconf.lualine")
